### ISSUE TITLE
使用QACTPBEE --userid 133496出错

### ISSUE THREAD

**Issue by bin-wang-sh** [yutiansut/QACTPBeeBroker#3]
要使用如下指令：
QACTPBEE --userid 133496
但发现QACTPBeeBroker没安装。安装如下软件包
#pip install https://github.com/yutiansut/QACTPBeeBroker/archive/master.zip
#pip install ctpbee
Collecting ctpbee
  Using cached https://files.pythonhosted.org/packages/36/95/7bd026fd24f5b9a1a35a49d9b2600fdd9ba6abfec2c314ed629f159379bf/ctpbee-0.30.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jo34lcm6/ctpbee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jo34lcm6/ctpbee/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-jo34lcm6/ctpbee/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jo34lcm6/ctpbee/setup.py", line 6, in <module>
        from ctpbee import __version__
      File "/tmp/pip-install-jo34lcm6/ctpbee/ctpbee/__init__.py", line 8, in <module>
        from ctpbee.app import CtpBee
      File "/tmp/pip-install-jo34lcm6/ctpbee/ctpbee/app.py", line 13, in <module>
        from ctpbee.constant import Exchange
      File "/tmp/pip-install-jo34lcm6/ctpbee/ctpbee/constant.py", line 5, in <module>
        from dataclasses import dataclass, asdict
    ModuleNotFoundError: No module named 'dataclasses'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
发现ctpbee出错。请求帮助？

**Comment by somewheve** [comment]
此问题已经被修复了 手动安装dataclasses就好了
